# Experiment 4: Markov Decision Process (MDP)

## Aim
To implement Markov Decision Process using Value Iteration.

## Theory
A Markov Decision Process (MDP) is defined by:
- States (S)
- Actions (A)
- Transition probabilities (P)
- Rewards (R)
- Policy (π)

The goal is to find an optimal policy that maximizes cumulative reward.

In [1]:
# Import Libraries
import numpy as np

## Step 1: Define Grid Environment

In [2]:
grid_size = 3

states = [(i, j) for i in range(grid_size) for j in range(grid_size)]
actions = ['up', 'down', 'left', 'right']

# Reward matrix
rewards = np.zeros((grid_size, grid_size))
rewards[2, 2] = 10  # Goal state

## Step 2: Initialize Value Function

In [3]:
V = np.zeros((grid_size, grid_size))

gamma = 0.9
theta = 0.001

## Step 3: Define Transition Function

In [4]:
def get_next_state(state, action):
    i, j = state

    if action == 'up':
        i = max(i - 1, 0)
    elif action == 'down':
        i = min(i + 1, grid_size - 1)
    elif action == 'left':
        j = max(j - 1, 0)
    elif action == 'right':
        j = min(j + 1, grid_size - 1)

    return (i, j)

## Step 4: Value Iteration Algorithm

In [5]:
while True:
    delta = 0

    for state in states:
        i, j = state
        v = V[i, j]

        values = []
        for action in actions:
            next_state = get_next_state(state, action)
            ni, nj = next_state

            value = rewards[ni, nj] + gamma * V[ni, nj]
            values.append(value)

        V[i, j] = max(values)
        delta = max(delta, abs(v - V[i, j]))

    if delta < theta:
        break

## Step 5: Display Value Function

In [6]:
print("Optimal Value Function:\n")
print(V)

Optimal Value Function:

[[72.89153585 80.99153585 89.99153585]
 [80.99153585 89.99153585 99.99153585]
 [89.99153585 99.99153585 99.99153585]]


## Step 6: Derive Optimal Policy

In [7]:
policy = {}

for state in states:
    i, j = state

    best_action = None
    best_value = -float('inf')

    for action in actions:
        next_state = get_next_state(state, action)
        ni, nj = next_state

        value = rewards[ni, nj] + gamma * V[ni, nj]

        if value > best_value:
            best_value = value
            best_action = action

    policy[state] = best_action

print("\nOptimal Policy:\n")
for state, action in policy.items():
    print(state, "->", action)


Optimal Policy:

(0, 0) -> down
(0, 1) -> down
(0, 2) -> down
(1, 0) -> down
(1, 1) -> down
(1, 2) -> down
(2, 0) -> right
(2, 1) -> right
(2, 2) -> down


## Conclusion
- Value Iteration successfully computes optimal values.
- The derived policy gives the best action for each state.
- MDP is useful for decision-making problems.